# Generated by Django 5.1.3 on 2024-12-05 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('age', models.IntegerField()),
                ('group', models.CharField(default='Unknown', max_length=255)),
                ('coin', models.IntegerField()),
                ('hobbi', models.CharField(max_length=256)),
                ('tolov', models.CharField(max_length=256)),
                ('filial', models.CharField(max_length=256)),
                ('study_time', models.CharField(max_length=256)),
                ('laptop', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': "O'quvchi",
                'verbose_name_plural': "O'quvchilar",
            },
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('age', models.IntegerField()),
                ('groups', models.CharField(default='Unknown', max_length=255)),
                ('salary', models.IntegerField()),
                ('work', models.CharField(max_length=256)),
                ('work_time', models.TimeField()),
                ('language', models.CharField(max_length=256)),
                ('filial', models.CharField(max_length=256)),
                ('extra_lesson', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': "O'qitovchi",
                'verbose_name_plural': "O'qitovchilar",
            },
        ),
    ]
