# Generated by Django 5.1.3 on 2024-12-07 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('age', models.IntegerField()),
                ('salary', models.IntegerField()),
                ('work', models.CharField(max_length=256)),
                ('work_time', models.TimeField()),
                ('filial', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Administrator',
                'verbose_name_plural': 'Administratorlar',
            },
        ),
        migrations.AlterField(
            model_name='students',
            name='study_time',
            field=models.TimeField(),
        ),
    ]
